kind: Pod
metadata:
  labels:
    foo: bar
spec:
  restartPolicy: Never
  containers:
  - image: daskdev/dask:latest
    imagePullPolicy: IfNotPresent
    args: [dask-worker, --nthreads, '2', --no-bokeh, --memory-limit, 1.5GB, --death-timeout, '60']
    name: dask
    resources:
      limits:
        cpu: "2"
        memory: 2G
      requests:
        cpu: "2"
        memory: 1.5G
